//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EtiquetasCI_EMMEntities : DbContext
    {
        public EtiquetasCI_EMMEntities()
            : base("name=EtiquetasCI_EMMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<sp_BTS_CalculaLostSize_Result2> sp_BTS_CalculaLostSize(Nullable<System.DateTime> fechaHoy)
        {
            var fechaHoyParameter = fechaHoy.HasValue ?
                new ObjectParameter("FechaHoy", fechaHoy) :
                new ObjectParameter("FechaHoy", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_BTS_CalculaLostSize_Result2>("sp_BTS_CalculaLostSize", fechaHoyParameter);
        }
    }
}
