//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTS.Models
{
    using System;
    
    public partial class sp_BTS_CalculaLostSize_Result2
    {
        public int JobNumber { get; set; }
        public Nullable<int> DieSet { get; set; }
        public string NoParte { get; set; }
        public string Descripcion { get; set; }
        public Nullable<decimal> Lunes_T { get; set; }
        public Nullable<decimal> Lunes_R { get; set; }
        public Nullable<decimal> Martes_T { get; set; }
        public Nullable<decimal> Martes_R { get; set; }
        public Nullable<decimal> Miercoles_T { get; set; }
        public Nullable<decimal> Miercoles_R { get; set; }
        public Nullable<decimal> Jueves_T { get; set; }
        public Nullable<decimal> Jueves_R { get; set; }
        public Nullable<decimal> Viernes_T { get; set; }
        public Nullable<decimal> Viernes_R { get; set; }
        public Nullable<decimal> Sabado_T { get; set; }
        public Nullable<decimal> Sabado_R { get; set; }
        public Nullable<decimal> Domingo_T { get; set; }
        public Nullable<decimal> Domingo_R { get; set; }
        public Nullable<decimal> Total_T { get; set; }
        public Nullable<decimal> Total_R { get; set; }
        public string Comentarios { get; set; }
        public Nullable<decimal> BTS { get; set; }
        public Nullable<int> PastDue { get; set; }
        public Nullable<int> Inventarios { get; set; }
        public Nullable<int> IdLinea { get; set; }
        public Nullable<bool> BanderaDia { get; set; }
    }
}
